# Generated by Django 3.0.2 on 2020-01-23 06:03

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIDR', netfields.fields.CidrAddressField(max_length=43)),
            ],
        ),
    ]
