# Generated by Django 3.0.2 on 2020-01-23 09:38

from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('IPAM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', netfields.fields.InetAddressField(max_length=39)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPAM.Subnet')),
            ],
        ),
    ]
